### ISSUE TITLE
show which rule/plugin is throwing the error/warning

### ISSUE THREAD

**Issue by AbdallahAbis** [fengzilong/eslint-formatter-mo#21]
when `eslint-formatter-mo` is used:
![Screen Shot 2022-04-17 at 16 00 39](https://user-images.githubusercontent.com/59185227/163722576-5e53c297-c329-4bed-ad0d-9603161f12ba.png)

When the formatter is not used:
![Screen Shot 2022-04-17 at 16 01 04](https://user-images.githubusercontent.com/59185227/163722596-cca6118b-8b71-4962-b700-c8f20ff16eee.png)

is there a config to show the rule along with the message?

**Comment by fengzilong** [comment]
Sorry I just saw this. It may be a bug I guess. will dig into it soon

**Comment by fengzilong** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9125255/187572861-d42f4961-7599-423d-8d02-88fd4d13ba4d.png">

implemented in `eslint-formatter-mo@1.2.0`
